# Generated by Django 5.0.7 on 2024-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_page_count_file_uuid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('PS', 'Printing Service'), ('BS', 'Binding Service'), ('PB', 'Printing + Binding'), ('OE', 'Other Essentials')], max_length=2),
        ),
    ]
