# Generated by Django 5.0.7 on 2024-07-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_url',
            new_name='url',
        ),
    ]
